/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.flight.status.api;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** A record for aircraft type */
@org.apache.avro.specific.AvroGenerated
public class AircraftType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 499278237085688363L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AircraftType\",\"namespace\":\"io.flight.status.api\",\"doc\":\"A record for aircraft type\",\"fields\":[{\"name\":\"iataMain\",\"type\":[\"null\",\"string\"],\"doc\":\"iata code\"},{\"name\":\"iataSub\",\"type\":[\"null\",\"string\"],\"doc\":\"iata code\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AircraftType> ENCODER =
      new BinaryMessageEncoder<AircraftType>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AircraftType> DECODER =
      new BinaryMessageDecoder<AircraftType>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AircraftType> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AircraftType> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AircraftType> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AircraftType>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AircraftType to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AircraftType from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AircraftType instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AircraftType fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** iata code */
   private java.lang.CharSequence iataMain;
  /** iata code */
   private java.lang.CharSequence iataSub;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AircraftType() {}

  /**
   * All-args constructor.
   * @param iataMain iata code
   * @param iataSub iata code
   */
  public AircraftType(java.lang.CharSequence iataMain, java.lang.CharSequence iataSub) {
    this.iataMain = iataMain;
    this.iataSub = iataSub;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return iataMain;
    case 1: return iataSub;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: iataMain = (java.lang.CharSequence)value$; break;
    case 1: iataSub = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'iataMain' field.
   * @return iata code
   */
  public java.lang.CharSequence getIataMain() {
    return iataMain;
  }


  /**
   * Sets the value of the 'iataMain' field.
   * iata code
   * @param value the value to set.
   */
  public void setIataMain(java.lang.CharSequence value) {
    this.iataMain = value;
  }

  /**
   * Gets the value of the 'iataSub' field.
   * @return iata code
   */
  public java.lang.CharSequence getIataSub() {
    return iataSub;
  }


  /**
   * Sets the value of the 'iataSub' field.
   * iata code
   * @param value the value to set.
   */
  public void setIataSub(java.lang.CharSequence value) {
    this.iataSub = value;
  }

  /**
   * Creates a new AircraftType RecordBuilder.
   * @return A new AircraftType RecordBuilder
   */
  public static io.flight.status.api.AircraftType.Builder newBuilder() {
    return new io.flight.status.api.AircraftType.Builder();
  }

  /**
   * Creates a new AircraftType RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AircraftType RecordBuilder
   */
  public static io.flight.status.api.AircraftType.Builder newBuilder(io.flight.status.api.AircraftType.Builder other) {
    if (other == null) {
      return new io.flight.status.api.AircraftType.Builder();
    } else {
      return new io.flight.status.api.AircraftType.Builder(other);
    }
  }

  /**
   * Creates a new AircraftType RecordBuilder by copying an existing AircraftType instance.
   * @param other The existing instance to copy.
   * @return A new AircraftType RecordBuilder
   */
  public static io.flight.status.api.AircraftType.Builder newBuilder(io.flight.status.api.AircraftType other) {
    if (other == null) {
      return new io.flight.status.api.AircraftType.Builder();
    } else {
      return new io.flight.status.api.AircraftType.Builder(other);
    }
  }

  /**
   * RecordBuilder for AircraftType instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AircraftType>
    implements org.apache.avro.data.RecordBuilder<AircraftType> {

    /** iata code */
    private java.lang.CharSequence iataMain;
    /** iata code */
    private java.lang.CharSequence iataSub;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.flight.status.api.AircraftType.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.iataMain)) {
        this.iataMain = data().deepCopy(fields()[0].schema(), other.iataMain);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.iataSub)) {
        this.iataSub = data().deepCopy(fields()[1].schema(), other.iataSub);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing AircraftType instance
     * @param other The existing instance to copy.
     */
    private Builder(io.flight.status.api.AircraftType other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.iataMain)) {
        this.iataMain = data().deepCopy(fields()[0].schema(), other.iataMain);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.iataSub)) {
        this.iataSub = data().deepCopy(fields()[1].schema(), other.iataSub);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'iataMain' field.
      * iata code
      * @return The value.
      */
    public java.lang.CharSequence getIataMain() {
      return iataMain;
    }


    /**
      * Sets the value of the 'iataMain' field.
      * iata code
      * @param value The value of 'iataMain'.
      * @return This builder.
      */
    public io.flight.status.api.AircraftType.Builder setIataMain(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.iataMain = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'iataMain' field has been set.
      * iata code
      * @return True if the 'iataMain' field has been set, false otherwise.
      */
    public boolean hasIataMain() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'iataMain' field.
      * iata code
      * @return This builder.
      */
    public io.flight.status.api.AircraftType.Builder clearIataMain() {
      iataMain = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'iataSub' field.
      * iata code
      * @return The value.
      */
    public java.lang.CharSequence getIataSub() {
      return iataSub;
    }


    /**
      * Sets the value of the 'iataSub' field.
      * iata code
      * @param value The value of 'iataSub'.
      * @return This builder.
      */
    public io.flight.status.api.AircraftType.Builder setIataSub(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.iataSub = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'iataSub' field has been set.
      * iata code
      * @return True if the 'iataSub' field has been set, false otherwise.
      */
    public boolean hasIataSub() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'iataSub' field.
      * iata code
      * @return This builder.
      */
    public io.flight.status.api.AircraftType.Builder clearIataSub() {
      iataSub = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AircraftType build() {
      try {
        AircraftType record = new AircraftType();
        record.iataMain = fieldSetFlags()[0] ? this.iataMain : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.iataSub = fieldSetFlags()[1] ? this.iataSub : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AircraftType>
    WRITER$ = (org.apache.avro.io.DatumWriter<AircraftType>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AircraftType>
    READER$ = (org.apache.avro.io.DatumReader<AircraftType>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.iataMain == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.iataMain);
    }

    if (this.iataSub == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.iataSub);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.iataMain = null;
      } else {
        this.iataMain = in.readString(this.iataMain instanceof Utf8 ? (Utf8)this.iataMain : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.iataSub = null;
      } else {
        this.iataSub = in.readString(this.iataSub instanceof Utf8 ? (Utf8)this.iataSub : null);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.iataMain = null;
          } else {
            this.iataMain = in.readString(this.iataMain instanceof Utf8 ? (Utf8)this.iataMain : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.iataSub = null;
          } else {
            this.iataSub = in.readString(this.iataSub instanceof Utf8 ? (Utf8)this.iataSub : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










