/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.flight.status.api;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** A record for route type */
@org.apache.avro.specific.AvroGenerated
public class Route extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2226381464148590256L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Route\",\"namespace\":\"io.flight.status.api\",\"doc\":\"A record for route type\",\"fields\":[{\"name\":\"destinations\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"doc\":\"The destination information\"},{\"name\":\"eu\",\"type\":[\"null\",\"string\"],\"doc\":\"An indicator for whether the route is within EU or not\"},{\"name\":\"visa\",\"type\":[\"null\",\"string\"],\"doc\":\"An indicator to check whether the route is required to have a visa or not\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Route> ENCODER =
      new BinaryMessageEncoder<Route>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Route> DECODER =
      new BinaryMessageDecoder<Route>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Route> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Route> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Route> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Route>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Route to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Route from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Route instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Route fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The destination information */
   private java.util.List<java.lang.CharSequence> destinations;
  /** An indicator for whether the route is within EU or not */
   private java.lang.CharSequence eu;
  /** An indicator to check whether the route is required to have a visa or not */
   private java.lang.CharSequence visa;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Route() {}

  /**
   * All-args constructor.
   * @param destinations The destination information
   * @param eu An indicator for whether the route is within EU or not
   * @param visa An indicator to check whether the route is required to have a visa or not
   */
  public Route(java.util.List<java.lang.CharSequence> destinations, java.lang.CharSequence eu, java.lang.CharSequence visa) {
    this.destinations = destinations;
    this.eu = eu;
    this.visa = visa;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return destinations;
    case 1: return eu;
    case 2: return visa;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: destinations = (java.util.List<java.lang.CharSequence>)value$; break;
    case 1: eu = (java.lang.CharSequence)value$; break;
    case 2: visa = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'destinations' field.
   * @return The destination information
   */
  public java.util.List<java.lang.CharSequence> getDestinations() {
    return destinations;
  }


  /**
   * Sets the value of the 'destinations' field.
   * The destination information
   * @param value the value to set.
   */
  public void setDestinations(java.util.List<java.lang.CharSequence> value) {
    this.destinations = value;
  }

  /**
   * Gets the value of the 'eu' field.
   * @return An indicator for whether the route is within EU or not
   */
  public java.lang.CharSequence getEu() {
    return eu;
  }


  /**
   * Sets the value of the 'eu' field.
   * An indicator for whether the route is within EU or not
   * @param value the value to set.
   */
  public void setEu(java.lang.CharSequence value) {
    this.eu = value;
  }

  /**
   * Gets the value of the 'visa' field.
   * @return An indicator to check whether the route is required to have a visa or not
   */
  public java.lang.CharSequence getVisa() {
    return visa;
  }


  /**
   * Sets the value of the 'visa' field.
   * An indicator to check whether the route is required to have a visa or not
   * @param value the value to set.
   */
  public void setVisa(java.lang.CharSequence value) {
    this.visa = value;
  }

  /**
   * Creates a new Route RecordBuilder.
   * @return A new Route RecordBuilder
   */
  public static io.flight.status.api.Route.Builder newBuilder() {
    return new io.flight.status.api.Route.Builder();
  }

  /**
   * Creates a new Route RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Route RecordBuilder
   */
  public static io.flight.status.api.Route.Builder newBuilder(io.flight.status.api.Route.Builder other) {
    if (other == null) {
      return new io.flight.status.api.Route.Builder();
    } else {
      return new io.flight.status.api.Route.Builder(other);
    }
  }

  /**
   * Creates a new Route RecordBuilder by copying an existing Route instance.
   * @param other The existing instance to copy.
   * @return A new Route RecordBuilder
   */
  public static io.flight.status.api.Route.Builder newBuilder(io.flight.status.api.Route other) {
    if (other == null) {
      return new io.flight.status.api.Route.Builder();
    } else {
      return new io.flight.status.api.Route.Builder(other);
    }
  }

  /**
   * RecordBuilder for Route instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Route>
    implements org.apache.avro.data.RecordBuilder<Route> {

    /** The destination information */
    private java.util.List<java.lang.CharSequence> destinations;
    /** An indicator for whether the route is within EU or not */
    private java.lang.CharSequence eu;
    /** An indicator to check whether the route is required to have a visa or not */
    private java.lang.CharSequence visa;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.flight.status.api.Route.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.destinations)) {
        this.destinations = data().deepCopy(fields()[0].schema(), other.destinations);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.eu)) {
        this.eu = data().deepCopy(fields()[1].schema(), other.eu);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.visa)) {
        this.visa = data().deepCopy(fields()[2].schema(), other.visa);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Route instance
     * @param other The existing instance to copy.
     */
    private Builder(io.flight.status.api.Route other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.destinations)) {
        this.destinations = data().deepCopy(fields()[0].schema(), other.destinations);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eu)) {
        this.eu = data().deepCopy(fields()[1].schema(), other.eu);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.visa)) {
        this.visa = data().deepCopy(fields()[2].schema(), other.visa);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'destinations' field.
      * The destination information
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getDestinations() {
      return destinations;
    }


    /**
      * Sets the value of the 'destinations' field.
      * The destination information
      * @param value The value of 'destinations'.
      * @return This builder.
      */
    public io.flight.status.api.Route.Builder setDestinations(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[0], value);
      this.destinations = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'destinations' field has been set.
      * The destination information
      * @return True if the 'destinations' field has been set, false otherwise.
      */
    public boolean hasDestinations() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'destinations' field.
      * The destination information
      * @return This builder.
      */
    public io.flight.status.api.Route.Builder clearDestinations() {
      destinations = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'eu' field.
      * An indicator for whether the route is within EU or not
      * @return The value.
      */
    public java.lang.CharSequence getEu() {
      return eu;
    }


    /**
      * Sets the value of the 'eu' field.
      * An indicator for whether the route is within EU or not
      * @param value The value of 'eu'.
      * @return This builder.
      */
    public io.flight.status.api.Route.Builder setEu(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.eu = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'eu' field has been set.
      * An indicator for whether the route is within EU or not
      * @return True if the 'eu' field has been set, false otherwise.
      */
    public boolean hasEu() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'eu' field.
      * An indicator for whether the route is within EU or not
      * @return This builder.
      */
    public io.flight.status.api.Route.Builder clearEu() {
      eu = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'visa' field.
      * An indicator to check whether the route is required to have a visa or not
      * @return The value.
      */
    public java.lang.CharSequence getVisa() {
      return visa;
    }


    /**
      * Sets the value of the 'visa' field.
      * An indicator to check whether the route is required to have a visa or not
      * @param value The value of 'visa'.
      * @return This builder.
      */
    public io.flight.status.api.Route.Builder setVisa(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.visa = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'visa' field has been set.
      * An indicator to check whether the route is required to have a visa or not
      * @return True if the 'visa' field has been set, false otherwise.
      */
    public boolean hasVisa() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'visa' field.
      * An indicator to check whether the route is required to have a visa or not
      * @return This builder.
      */
    public io.flight.status.api.Route.Builder clearVisa() {
      visa = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Route build() {
      try {
        Route record = new Route();
        record.destinations = fieldSetFlags()[0] ? this.destinations : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[0]);
        record.eu = fieldSetFlags()[1] ? this.eu : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.visa = fieldSetFlags()[2] ? this.visa : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Route>
    WRITER$ = (org.apache.avro.io.DatumWriter<Route>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Route>
    READER$ = (org.apache.avro.io.DatumReader<Route>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.destinations.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.destinations) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    if (this.eu == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.eu);
    }

    if (this.visa == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.visa);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.destinations;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("destinations").schema());
        this.destinations = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.eu = null;
      } else {
        this.eu = in.readString(this.eu instanceof Utf8 ? (Utf8)this.eu : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.visa = null;
      } else {
        this.visa = in.readString(this.visa instanceof Utf8 ? (Utf8)this.visa : null);
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.destinations;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("destinations").schema());
            this.destinations = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.eu = null;
          } else {
            this.eu = in.readString(this.eu instanceof Utf8 ? (Utf8)this.eu : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.visa = null;
          } else {
            this.visa = in.readString(this.visa instanceof Utf8 ? (Utf8)this.visa : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










