flight-status:
  api: https://api.schiphol.nl/public-flights/flights
  version: v4
  app:
    id: <id>
    key: <key>

spring:
  kafka:
    properties:
      # confluent cloud config
      bootstrap.servers: <confluent-kafka-server>
      sasl.mechanism: PLAIN
      sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required
  username='username' password='password';"
      security.protocol: SASL_SSL
      # confluent schema registry
      schema.registry.url: <confluent-schema-registry>
      basic.auth.credentials.source: USER_INFO
      schema.registry.basic.auth.user.info: <user-info>
      streams:
        replication-factor: 3
  cloud:
    stream:
      function:
        definition: produceFlightStatusInformation;consumeFlightStatusInformation
      bindings:
        # kafka producer
        produceFlightStatusInformation-out-0:
          binder: kafka
          destination: flightstatus
          content-type: application/*+avro
          producer:
            partition-count: 4
            useNativeEncoding: true
        consumeFlightStatusInformation-in-0:
          binder: kafka
          destination: flightstatus
          content-type: application/*+avro
          group: FlightStatusOutputter
      kafka:
        binder:
          producer-properties:
            key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
          consumer-properties:
            key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            specific.avro.reader: true
logging:
  level: info